import { Prisma, Transaction, TransactionType } from "@prisma/client";
import { prisma } from "../lib/db";
import { ApiError } from "../lib/ApiError";
import { cacheDel } from "../lib/redis";
import { analyzeNewTransaction } from "./anomaly.service";

export interface ListTransactionsQuery {
  page: number;
  limit: number;
  type?: TransactionType;
  category?: string;
  search?: string;
  sortBy: "date" | "amount" | "createdAt";
  sortOrder: "asc" | "desc";
  startDate?: Date;
  endDate?: Date;
}

export interface CreateTransactionInput {
  amount: number;
  type: TransactionType;
  category: string;
  description?: string;
  date: Date;
}

export type UpdateTransactionInput = Partial<CreateTransactionInput> & {
  version?: number;
};

/** Thrown when the client sends a version that doesn't match the stored one. */
export class VersionConflictError extends Error {
  constructor(public readonly currentVersion: number) {
    super("Version conflict");
    this.name = "VersionConflictError";
  }
}

/** Thrown when the client doesn't send a version at all. */
export class VersionRequiredError extends Error {
  constructor() {
    super("Version is required");
    this.name = "VersionRequiredError";
  }
}

/** Prisma Decimal serializes as a string; the API contract exposes a number. */
export const serializeTransaction = (tx: Transaction) => ({
  ...tx,
  amount: Number(tx.amount),
});

const invalidateDashboardCache = () => cacheDel("dashboard:*");

export async function listTransactions(q: ListTransactionsQuery) {
  const where: Prisma.TransactionWhereInput = {};

  if (q.type) where.type = q.type;
  if (q.category) where.category = { equals: q.category, mode: "insensitive" };
  if (q.search) {
    where.OR = [
      { description: { contains: q.search, mode: "insensitive" } },
      { category: { contains: q.search, mode: "insensitive" } },
    ];
  }
  if (q.startDate || q.endDate) {
    where.date = {};
    if (q.startDate) where.date.gte = q.startDate;
    if (q.endDate) where.date.lte = q.endDate;
  }

  const skip = (q.page - 1) * q.limit;

  const [items, total] = await Promise.all([
    prisma.transaction.findMany({
      where,
      orderBy: { [q.sortBy]: q.sortOrder },
      skip,
      take: q.limit,
    }),
    prisma.transaction.count({ where }),
  ]);

  return {
    items,
    pagination: {
      page: q.page,
      limit: q.limit,
      total,
      totalPages: Math.max(1, Math.ceil(total / q.limit)),
    },
  };
}

export async function getTransactionById(id: string) {
  const tx = await prisma.transaction.findUnique({ where: { id } });
  if (!tx) throw ApiError.notFound("Transaction not found");
  return tx;
}

export async function createTransaction(input: CreateTransactionInput) {
  // `version` defaults to 1 at the database level.
  const tx = await prisma.transaction.create({
    data: {
      amount: input.amount,
      type: input.type,
      category: input.category,
      description: input.description || null,
      date: input.date,
    },
  });

  await invalidateDashboardCache();

  // Fire-and-forget-ish, but awaited so the response reflects any
  // notifications generated by this transaction. Failures here must never
  // fail the transaction write itself.
  try {
    await analyzeNewTransaction(tx);
  } catch (err) {
    console.error("[anomaly] analysis failed (non-fatal):", err);
  }

  return tx;
}

export async function updateTransaction(
  id: string,
  input: UpdateTransactionInput,
) {
  // 428: the client must tell us which version it last saw.
  if (input.version === undefined || input.version === null) {
    throw new VersionRequiredError();
  }

  const existing = await prisma.transaction.findUnique({ where: { id } });
  if (!existing) throw ApiError.notFound("Transaction not found");

  // Atomic compare-and-set. The version check, the field updates and the
  // version increment all happen in ONE SQL UPDATE ... WHERE id = ? AND
  // version = ?, so concurrent writers can't both succeed.
  const result = await prisma.transaction.updateMany({
    where: { id, version: input.version },
    data: {
      ...(input.amount !== undefined ? { amount: input.amount } : {}),
      ...(input.type !== undefined ? { type: input.type } : {}),
      ...(input.category !== undefined ? { category: input.category } : {}),
      ...(input.description !== undefined
        ? { description: input.description || null }
        : {}),
      ...(input.date !== undefined ? { date: input.date } : {}),
      version: { increment: 1 },
    },
  });

  if (result.count === 0) {
    // Stale version (or we lost a race). Nothing was changed.
    const current = await prisma.transaction.findUnique({
      where: { id },
      select: { version: true },
    });
    if (!current) throw ApiError.notFound("Transaction not found");
    throw new VersionConflictError(current.version);
  }

  const tx = await prisma.transaction.findUniqueOrThrow({ where: { id } });

  await invalidateDashboardCache();
  return tx;
}

export async function deleteTransaction(id: string) {
  const existing = await prisma.transaction.findUnique({ where: { id } });
  if (!existing) throw ApiError.notFound("Transaction not found");

  await prisma.transaction.delete({ where: { id } });
  await invalidateDashboardCache();
}
